[ceph]
mgr_ips = 10.230.10.11,10.230.10.12

[auth]
username = admin
password = sms980502!

[webhook]
platform = slack
webhook_url = https://mattermost.somansa.com/api/v4/posts
bot_token = 6htfppanstn5jmxcf65dop88th
channel_id = "#ceph-infra"

[cooldown]
# minutes
cluster_alert = 60
conn_err = 30
auth_err = 30

[monitor]
refresh_interval = 180