import requests
import io
from .base import BaseNotifier

class SlackNotifierBase(BaseNotifier):
    """페이로드 블록킷을 생성하는 베이스 클래스"""
    def _create_payload(self, severity, detail, channel_id, more_info):
        if isinstance(more_info, dict):
            # PG 필터링 (정상이 아닌 것만)
            pg_raw = more_info.get("pg_info_str", "No PG info")
            pg_list = [p.strip() for p in pg_raw.split(',') if p.strip()]
            issue_pgs = [p for p in pg_list if 'active+clean' not in p]
            pg_summary = "✅ *All PGs Healthy*" if not issue_pgs else "⚠️ *Issues:* " + ", ".join(issue_pgs)

            # Top Issues 가공 (빈 줄 제거 및 요약)
            detail_lines = [line.strip() for line in detail.split('\n') if line.strip()]
            short_detail = "\n".join([f"• {line}" for line in detail_lines[:3]])
            has_more = len(detail_lines) > 3

            # 깨지지 않는 바 그래프
            total_gb = int(more_info.get("total_gb", 1))
            used_gb = int(more_info.get("total_used_raw_gb", 0))
            used_per = (used_gb / total_gb * 100) if total_gb > 0 else 0
            bar_cnt = int(used_per / 10)
            capacity_display = f"`{'■' * bar_cnt}{'□' * (10 - bar_cnt)}` *{used_per:.2f}%*"
            osd_status = f"{more_info.get('osd_up_count')} UP / {more_info.get('osd_in_count')} IN"
        else:
            pg_summary = "N/A"; short_detail = str(more_info); osd_status = "N/A"; capacity_display = "N/A"; has_more = False

        blocks = [
            {"type": "header", "text": {"type": "plain_text", "text": "🚨 Ceph Cluster Alert", "emoji": True}},
            {"type": "divider"},
            {"type": "section", "fields": [
                {"type": "mrkdwn", "text": f"*Status:*\n`{severity}`"},
                {"type": "mrkdwn", "text": f"*OSD Status:*\n`{osd_status}`"}
            ]},
            {"type": "section", "text": {"type": "mrkdwn", "text": f"*Usage:*\n{capacity_display}"}},
            {"type": "divider"},
            {"type": "section", "text": {"type": "mrkdwn", "text": f"*Top Issues:*\n{short_detail}"}},
            {"type": "section", "text": {"type": "mrkdwn", "text": f"*PG Health:*\n{pg_summary}"}}
        ]

        # [수정] 외부 접근 불가한 대시보드 주소 대신 안내 문구 추가
        blocks.append({"type": "divider"})
        blocks.append({
            "type": "context", 
            "elements": [{"type": "mrkdwn", "text": "📄 *상세 정보(PG/OSD)는 아래 첨부된 HTML 파일을 확인하세요.*"}]
        })
        blocks.append({
            "type": "context", 
            "elements": [{"type": "mrkdwn", "text": "Powered by Jinseop.song - System Engineering Team, Infra Dept."}]
        })

        return {"channel": channel_id, "username": "ceph_monitor_bot", "icon_emoji": ":ceph_logo:", "blocks": blocks}

    def _generate_html_report(self, severity, more_info):
        """상세 정보를 담은 HTML 리포트 생성"""
        health_detail = more_info.get("health_detail_raw", "상세 데이터 없음")
        osd_df = more_info.get("osd_df_raw", "상세 데이터 없음")
        
        html = f"""
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {{ background-color: #1e1e1e; color: #d4d4d4; font-family: 'Courier New', monospace; padding: 20px; line-height: 1.5; }}
                h2 {{ color: #ff2d00; border-bottom: 1px solid #444; padding-bottom: 10px; }}
                h3 {{ color: #569cd6; margin-top: 30px; }}
                pre {{ background-color: #2d2d2d; padding: 15px; border-radius: 5px; overflow-x: auto; white-space: pre-wrap; border: 1px solid #3c3c3c; }}
                .status-box {{ display: inline-block; padding: 5px 10px; border-radius: 3px; background-color: #4e1a1a; color: #ff8888; font-weight: bold; }}
            </style>
        </head>
        <body>
            <h2>🚨 Ceph 상세 분석 리포트</h2>
            <div>상태: <span class="status-box">{severity}</span></div>
            
            <h3>[1] Ceph Health Detail</h3>
            <pre>{health_detail}</pre>
            
            <h3>[2] Ceph OSD DF Status</h3>
            <pre>{osd_df}</pre>
            
            <footer style="margin-top: 50px; font-size: 0.8em; color: #666;">
                Generated by Ceph Monitor Bot | Powered by Jinseop.song
            </footer>
        </body>
        </html>
        """
        return html

class SlackBotNotifier(SlackNotifierBase):
    """API 방식 (xoxb 토큰) - 메시지 전송 + 파일 업로드 가능"""
    def __init__(self, token, channel_id):
        self.token, self.channel_id = token, channel_id

    def send(self, severity, detail, more_info=None):
        # 1. 요약 알림 전송
        url = "https://slack.com/api/chat.postMessage"
        headers = {"Authorization": f"Bearer {self.token}", "Content-Type": "application/json"}
        payload = self._create_payload(severity, detail, self.channel_id, more_info)
        requests.post(url, headers=headers, json=payload, timeout=5)

        # 2. 상세 정보 HTML 파일 업로드 (Outbound 방식이라 VPN 우회 가능)
        if more_info and isinstance(more_info, dict):
            html_content = self._generate_html_report(severity, more_info)
            upload_url = "https://slack.com/api/files.upload"
            
            # 메모리에서 즉시 파일 생성
            file_obj = io.BytesIO(html_content.encode('utf-8'))
            
            files = {
                'file': (f"Ceph_Detail_{severity}.html", file_obj, "text/html")
            }
            data = {
                "token": self.token,
                "channels": self.channel_id,
                "initial_comment": "🔍 **Ceph Full Scan 리포트가 반출되었습니다.**",
                "title": f"Ceph_Detail_{severity}.html"
            }
            try:
                requests.post(upload_url, data=data, files=files, timeout=15)
            except Exception as e:
                print(f"HTML 리포트 반출 실패: {e}")

class SlackWebhookNotifier(SlackNotifierBase):
    """웹훅 방식 (Webhook URL) - 메시지 전송만 가능"""
    def __init__(self, url, channel_id):
        self.url, self.channel_id = url, channel_id

    def send(self, severity, detail, more_info=None):
        payload = self._create_payload(severity, detail, self.channel_id, more_info)
        requests.post(self.url, json=payload, timeout=5)